all:
	rm -fr test-conference/
	../../../tools/test-data/jsonapi-get --output-directory=test-conference --file-url-pattern='/images|files/' --output-filename=conference.json --base-url=/data 'https://conticki.srvitkphp73stg.itkdev.dk/api/conference/a84ab2bb-432e-40f0-9de8-2bb709a8842d?include=organizers,sponsors'
