all:
	rm -fr the-first-conference/
	../../../tools/test-data/jsonapi-get --output-directory=the-first-conference --file-url-pattern='/images|files/' 'https://admin.os2conticki.srvitkhulk.itkdev.dk/da/api/conference/ffb771b5-5748-4724-a56c-1d18f2b44c0e?include=organizers' --output-filename=conference.json --base-url=/data
